on:
    push:
        branches:
            - main
    pull_request:

env:
  flutter_version: "2.x"
  java_version: "12.x"

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: github.ref != 'refs/heads/main'
        steps:
            - name: "Checkout"
              uses: actions/checkout@main
            - uses: actions/setup-java@v1
              with:
                  java-version: ${{ env.java_version }}
            - name: Cache Flutter dependencies
              uses: actions/cache@v1
              with:
                path: /opt/hostedtoolcache/flutter
                key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
            - uses: subosito/flutter-action@v1
              with:
                  flutter-version: ${{ env.flutter_version }}
            - run: flutter pub get
            - run: flutter test
    build:
        name: Build for Android
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout main
              uses: actions/checkout@main
              with:
                  ref: main
            - uses: actions/setup-java@v1
              with:
                  java-version: ${{ env.java_version }}
            - name: Cache Flutter dependencies
              uses: actions/cache@v1
              with:
                path: /opt/hostedtoolcache/flutter
                key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
            - uses: subosito/flutter-action@v1
              with:
                  flutter-version: ${{ env.flutter_version }}
            - run: flutter pub get
            - run: flutter test
            - run: flutter build apk
            - run: flutter build appbundle
    build:
        name: Build for iOS
        runs-on: macos-latest
        timeout-minutes: 5
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout main
              uses: actions/checkout@main
              with:
                  ref: main
            - uses: actions/setup-java@v1
              with:
                  java-version: ${{ env.java_version }}
            - name: Cache Flutter dependencies
              uses: actions/cache@v1
              with:
                path: /opt/hostedtoolcache/flutter
                key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
            - uses: subosito/flutter-action@v1
              with:
                  flutter-version: ${{ env.flutter_version }}
            - run: flutter pub get
            - run: flutter build ios --release --no-codesign
